string gripper_frame        # Frame (eg grasp_frame) with which to align wipe frame
float64 z_offset            # Offset by which to move frame for better grasping (assumes +z normal-ish to and into table)
---
string wipe_frame           # Name of output frame
---
int64 data_points           # Number of images used so far to localize wipe